### ISSUE TITLE
Question on running get-shellcontent.ps1

### ISSUE THREAD

**Issue by mark-hallman** [JavelinNetworks/IR-Tools#1]
Hello,

Trying to give the get-shellcontent.ps1 script a test drive.  Testing in Win10 Pro & Win10 Enterprise.  When I run the script I just get the Powershell prompt back.  No output, no errors.  I have a couple of cmd shells and PowerShell windows open.  I have executed a few simple commands and Regedit.  I have run get-shellcontent.pst with no arguments and with the processid argument.  I'm probably missing something very basic.  Can you point me in the right direction?

Thanks.

-Mark

**Comment by javelin-networks** [comment]
Hey Mark,

You can't run the script explicitly from its path, please use Import-Module to import the script to your powershell before executing it.
